### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException after opening application

### ISSUE THREAD

**Issue by lalili** [otros-systems/otroslogviewer#395]
When I open the tool, below exception is shown. After clicking OK the log viewer works.
thanks!

![2016-06-09_12-10-53](https://cloud.githubusercontent.com/assets/11541573/15937006/442eb36a-2e3b-11e6-957e-206e57f84ecc.png)
![2016-06-09_12-10-55](https://cloud.githubusercontent.com/assets/11541573/15937050/634eab88-2e3b-11e6-86a8-c89426f77b2d.png)

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at javax.swing.JTabbedPane.getComponentAt(JTabbedPane.java:1224)
	at pl.otros.logview.gui.OtrosApplication.getSelectedLogViewPanel(OtrosApplication.java:100)
	at pl.otros.logview.gui.LogViewMainFrame$4.performActionHook(LogViewMainFrame.java:487)
	at pl.otros.logview.gui.util.DelayedSwingInvoke.lambda$performAction$7(DelayedSwingInvoke.java:37)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:27)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by otros-systems** [comment]
Please use version 1.4.1 from https://sourceforge.net/projects/otroslogviewer/

**Comment by lalili** [comment]
I still see the same exception after upgrade to 1.4.1. Here is the latest exception:

`java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at javax.swing.JTabbedPane.getComponentAt(JTabbedPane.java:1224)
	at pl.otros.logview.api.OtrosApplication.getSelectedLogViewPanel(OtrosApplication.java:101)
	at pl.otros.logview.gui.LogViewMainFrame$4.performActionHook(LogViewMainFrame.java:483)
	at pl.otros.logview.gui.util.DelayedSwingInvoke.lambda$performAction$26(DelayedSwingInvoke.java:37)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:26)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by otros-systems** [comment]
This is a different issue. Search field was trying to get Log Panel and add search occurence on scrolling pane. But there was no Log Panel and it get exception.
This issue will be fixed in 1.4.2. You can build from sources and test.
