### ISSUE TITLE
Updating log event details takes several seconds when message has an throwable

### ISSUE THREAD

**Issue by gerwinjansen** [otros-systems/otroslogviewer#433]
### Steps to reproduce
1. Tail a log with a log event which has a throwable with many stacktrace elements.
2. When selecting the event in the table, the details pane shows '"Updating log event details..." for 5-6 seconds.
3. After that the message is shown properly

### Workaround
Untick the 'Stacktrace with message' formatter in the message detail pane

### Analysis
For every line with a stacktrace element, Otros tries to contact the IDE. When the IDE is down, it times out after 150 milliseconds. With multiple stacktrace elements, that adds up to multiple seconds.
See below exception for more details.

```
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 150 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at pl.otros.logview.gui.services.jumptocode.JumpToCodeClient.executeAndGetContent(JumpToCodeClient.java:162)
	at pl.otros.logview.gui.services.jumptocode.JumpToCodeClient.lambda$0(JumpToCodeClient.java:48)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at pl.otros.logview.gui.services.jumptocode.JumpToCodeClient.getContent(JumpToCodeClient.java:46)
	at pl.otros.logview.gui.services.jumptocode.JumpToCodeServiceImpl.getContent(JumpToCodeServiceImpl.java:68)
	at pl.otros.logview.api.services.JumpToCodeService.getContentOptional(JumpToCodeService.java:33)
	at java.util.Optional.flatMap(Optional.java:241)
	at pl.otros.logview.gui.message.stacktracecode.StackTraceFormatter.addCodeToLine(StackTraceFormatter.java:56)
	at pl.otros.logview.gui.message.stacktracecode.StackTraceFormatter.format(StackTraceFormatter.java:43)
	at pl.otros.logview.gui.message.update.MessageUpdateUtils.lambda$0(MessageUpdateUtils.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	... 26 more
``

**Comment by otrebski** [comment]
Thanks @gerwinjansen for finding this.
Idea availability can be check by calling `jumpToCodeService.isIdeAvailable();`. This check can be inserted in https://github.com/otros-systems/otroslogviewer/blob/master/OtrosLogViewer-app/src/main/java/pl/otros/logview/gui/message/stacktracecode/StackTraceFormatter.java#L34 and and call `addCodeToLine` only if IDE is available.

Do you want to create pull request ?

**Comment by gerwinjansen** [comment]
Ok, thanks for the explanation. I will fix it.
