### ISSUE TITLE
Decompressing "gziped" logs on the fly is not working for various issues

### ISSUE THREAD

**Issue by kvokacka** [otros-systems/otroslogviewer#452]
I found problems with gziped support neither dropping gzipped file nor http link to gzipped file to OVL worked on my computer. 
Affected version 1.4.6.
System: Windows 10

Steps to reproduce:

1. drag and drop gzipped file to OVL and file is not processed at all.
Exception in log: 
`Logger name: pl.otros.logview.logloader.basic.LoadingRunnable
Message: Error when reading log
java.io.IOException: pl.otros.logview.api.io.ObservableInputStreamImpl.read() returned value out of range -1..255: -117
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:272)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at pl.otros.logview.api.io.Utils.reloadFileObject(Utils.java:191)
	at pl.otros.logview.logloader.basic.LoadingRunnable.runWithVfs(LoadingRunnable.java:118)
	at pl.otros.logview.logloader.basic.LoadingRunnable.run(LoadingRunnable.java:56)
	at java.lang.Thread.run(Thread.java:745)`

2. drag and drop URL on gzipped file from browser and MessageBox appeared "Problem during drag and drop of string: null" 
Exception in logs:
`Logger name: pl.otros.logview.gui.actions.read.DragAndDropFilesHandler
Message: Problem dropping something on the GUI: null
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.regex.Pattern.matches(Pattern.java:1134)
	at pl.otros.logview.api.io.Utils.getFileObjectShortName(Utils.java:294)
	at pl.otros.logview.gui.actions.read.DragAndDropFilesHandler.openLogFile(DragAndDropFilesHandler.java:272)
	at pl.otros.logview.gui.actions.read.DragAndDropFilesHandler.tryToImportUrl(DragAndDropFilesHandler.java:215)
	at pl.otros.logview.gui.actions.read.DragAndDropFilesHandler.importUrl(DragAndDropFilesHandler.java:179)
	at pl.otros.logview.gui.actions.read.DragAndDropFilesHandler.importData(DragAndDropFilesHandler.java:117)
	at javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1544)
	at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
	at javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:26)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
The latter problem looks similar as somebody experienced on Mac OS in issue #446.

**Comment by kvokacka** [comment]
I created a patch that solved those problem for me and also added a new property "trimUnmatchedLines" to Log4jPatternMultilineLogParser that enable or disable trimming of unmatched lines. I created one more test in LoadingRunnableTest for gzipped files that was failing before I made changes to Utils.reloadFileObject. 
[patch.zip](https://github.com/otros-systems/otroslogviewer/files/1627352/patch.zip)

**Comment by otrebski** [comment]
Thanks.
I have applied patch.
