### ISSUE TITLE
Importing log4j xml fails when it contains binary data

### ISSUE THREAD

**Issue by gerwinjansen** [otros-systems/otroslogviewer#471]
When a log message contains binary data, it could result in invalid xml characters.
Parsing such a log results in a exception
`Caused by: java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 46; An invalid XML character (Unicode: 0xfffe) was found in the CDATA section.
	at pl.otros.logview.importer.log4jxml.XMLDecoder.parse(XMLDecoder.java:175)
	at pl.otros.logview.importer.log4jxml.XMLDecoder.decodeEvents(XMLDecoder.java:299)
	at pl.otros.logview.importer.log4jxml.Log4jXmlLogImporter.importLogs(Log4jXmlLogImporter.java:62)
	... 27 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 46; An invalid XML character (Unicode: 0xfffe) was found in the CDATA section.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at pl.otros.logview.importer.log4jxml.XMLDecoder.parseString(XMLDecoder.java:182)
	at pl.otros.logview.importer.log4jxml.XMLDecoder.parse(XMLDecoder.java:167)
	... 29 more
`
Invalid characters need to be replaced by a marker character, so parsing can continue.

**Comment by otrebski** [comment]
Thanks @gerwinjansen
