### ISSUE TITLE
Can't launch viewer (olv-1.4.8.zip) on Mac OS X

### ISSUE THREAD

**Issue by slobokot** [otros-systems/otroslogviewer#504]
Fails with

```
Caused by: java.lang.NullPointerException
	at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)
	at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:661)
```

[olv-sergiy.log](https://github.com/otros-systems/otroslogviewer/files/1981440/olv-sergiy.log)

**Comment by otros-systems** [comment]
Thanks @slobokot. Will take a look

**Comment by otros-systems** [comment]
@slobokot please download version 1.4.9

**Comment by cgudrian** [comment]
I experience this error on Windows 10 with OLV 1.4.9.
