### ISSUE TITLE
NullPointerException on Multimonitor environment

### ISSUE THREAD

**Issue by svennissel** [otros-systems/otroslogviewer#525]
System: Windows 10 
Monitors: 3 with different resolutions
Java Version: 8
Sometimes on loading big files an moving mouse same time i get a NullPointerException 
`java.lang.NullPointerException

               at java.awt.Component.findUnderMouseInWindow(Component.java:1349)

               at java.awt.Component.getMousePosition(Component.java:1397)

               at org.jdesktop.swingx.rollover.RolloverProducer.updateRollover(RolloverProducer.java:216)

               at org.jdesktop.swingx.rollover.RolloverProducer.componentMoved(RolloverProducer.java:209)

               at java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:169)

               at java.awt.Component.processComponentEvent(Component.java:6368)

               at java.awt.Component.processEvent(Component.java:6319)

               at java.awt.Container.processEvent(Container.java:2239)

               at java.awt.Component.dispatchEventImpl(Component.java:4889)

               at java.awt.Container.dispatchEventImpl(Container.java:2297)

               at java.awt.Component.dispatchEvent(Component.java:4711)

               at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)

               at java.awt.EventQueue.access$500(EventQueue.java:97)

               at java.awt.EventQueue$3.run(EventQueue.java:709)

               at java.awt.EventQueue$3.run(EventQueue.java:703)

               at java.security.AccessController.doPrivileged(Native Method)

               at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

               at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)

               at java.awt.EventQueue$4.run(EventQueue.java:733)

               at java.awt.EventQueue$4.run(EventQueue.java:731)

               at java.security.AccessController.doPrivileged(Native Method)

               at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

               at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)

               at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:26)

               at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

               at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

               at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

               at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

               at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

               at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
I seams to be a AWT Bug: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6840067

**Comment by svennissel** [comment]
Why didn't you merge 35451ff? I got often the NullPointerException with the application.

**Comment by otros-systems** [comment]
It is merged. @svennissel can you check if master is working fine?

**Comment by svennissel** [comment]
I have tested it some days and i found the warning in the log. The fix works for me
