### ISSUE TITLE
Closing log file tab doesn't close the file itself

### ISSUE THREAD

**Issue by KDean-Dolphin** [otros-systems/otroslogviewer#536]
This is using v. 1.4.11. The steps here are particular to Windows because Windows is more aggressive about checking for files in use.

1. Open a log file (the ones I have were created with the standard Java logging package).
2. Press the '-' in the tab to close the file. Confirm closing it.

Now try to do something with the file in the operating system (e.g. renaming it or deleting it). Permission will be denied because the file is in use.

Please fix it so that closing the tab closes the file properly.

**Comment by Qwertovsky** [comment]
AFAIK, it is problem within Java.
On Windows logger can't rotate file, which I tail with java program.

**Comment by KDean-Dolphin** [comment]
It's not a problem with Java. The file is not being properly closed when the '-' in the tab is pressed. I've written many Java programs that read files and never had the files locked after I closed them in the Java program.

**Comment by svennissel** [comment]
I have the same error, but did not find a way to fix it.

**Comment by wlfbck** [comment]
I'm taking a look into the problem here, but since i'm not familiar with the code of OLV, i'll just document the steps here so maybe someone can actually take care of it incase i cannot.

1. First step is downloading https://github.com/jenkinsci/lib-file-leak-detector
2. Afterwards, start OLV, get the process id (via task manager or whatever)
3. Attach file leak detector to it via `java -jar .\file-leak-detector-1.15-jar-with-dependencies.jar PID_HERE trace,threshold=1,http=1337`
4. Access the list live via http://localhost:1337/
5. Notice the result below, after opening and closing a single log.
6. Notice there is actually two different leaks of the FileDescriptor happening.

C:\Temp\system.log is the log file i opened.

```
7 descriptors are open
#1 socket to /127.0.0.1:7434 by thread:Thread-9 on Tue Aug 23 19:58:14 CEST 2022
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:413)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
	at java.net.ServerSocket.accept(ServerSocket.java:528)
	at org.kohsuke.file_leak_detector.AgentMain.lambda$runHttpServer$2(AgentMain.java:182)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
#2 C:\WINDOWS\Fonts\COUR.TTF by thread:AWT-EventQueue-0 on Tue Aug 23 19:54:57 CEST 2022
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:244)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
	at sun.font.TrueTypeFont$1.run(TrueTypeFont.java:321)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.TrueTypeFont.open(TrueTypeFont.java:317)
	at sun.font.TrueTypeFont.verify(TrueTypeFont.java:518)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:207)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:188)
	at sun.font.SunFontManager.registerFontFile(SunFontManager.java:1157)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1096)
	at sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:287)
	at sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
	at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:82)
	at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:97)
	at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
	at sun.font.FontDesignMetrics.<init>(FontDesignMetrics.java:350)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.GlyphPainter1.sync(GlyphPainter1.java:226)
	at javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:59)
	at javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:592)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:732)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#3 C:\Temp\system.log by thread:AWT-EventQueue-0 on Tue Aug 23 19:54:54 CEST 2022
	at java.io.FileInputStream.<init>(FileInputStream.java:139)
	at org.apache.commons.vfs2.provider.local.LocalFile.doGetInputStream(LocalFile.java:105)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1197)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1184)
	at org.apache.commons.vfs2.provider.DefaultFileContent.buildInputStream(DefaultFileContent.java:500)
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:342)
	at pl.otros.logview.api.io.LoadingInfo.<init>(LoadingInfo.java:76)
	at pl.otros.logview.api.io.LoadingInfo.<init>(LoadingInfo.java:49)
	at pl.otros.logview.gui.actions.TailLogActionListener.openFileObjectInTailMode(TailLogActionListener.java:89)
	at pl.otros.logview.gui.actions.TailLogActionListener.doOpenChooseFileDialog(TailLogActionListener.java:78)
	at pl.otros.logview.gui.actions.TailLogActionListener.actionPerformedHook(TailLogActionListener.java:65)
	at pl.otros.logview.api.gui.OtrosAction.actionPerformed(OtrosAction.java:61)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:108)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#4 C:\WINDOWS\Fonts\SYMBOL.TTF by thread:AWT-EventQueue-0 on Tue Aug 23 19:54:57 CEST 2022
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:244)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
	at sun.font.TrueTypeFont$1.run(TrueTypeFont.java:321)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.TrueTypeFont.open(TrueTypeFont.java:317)
	at sun.font.TrueTypeFont.verify(TrueTypeFont.java:518)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:207)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:188)
	at sun.font.SunFontManager.registerFontFile(SunFontManager.java:1157)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1096)
	at sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:287)
	at sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
	at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:82)
	at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:97)
	at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
	at sun.font.FontDesignMetrics.<init>(FontDesignMetrics.java:350)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.GlyphPainter1.sync(GlyphPainter1.java:226)
	at javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:59)
	at javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:592)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:732)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#5 C:\WINDOWS\Fonts\WINGDING.TTF by thread:AWT-EventQueue-0 on Tue Aug 23 19:54:57 CEST 2022
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:244)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
	at sun.font.TrueTypeFont$1.run(TrueTypeFont.java:321)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.TrueTypeFont.open(TrueTypeFont.java:317)
	at sun.font.TrueTypeFont.verify(TrueTypeFont.java:518)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:207)
	at sun.font.TrueTypeFont.<init>(TrueTypeFont.java:188)
	at sun.font.SunFontManager.registerFontFile(SunFontManager.java:1157)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1096)
	at sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:287)
	at sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
	at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:82)
	at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:97)
	at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
	at sun.font.FontDesignMetrics.<init>(FontDesignMetrics.java:350)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.GlyphPainter1.sync(GlyphPainter1.java:226)
	at javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:59)
	at javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:592)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:732)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#6 C:\Temp\system.log by thread:AWT-EventQueue-0 on Tue Aug 23 19:54:54 CEST 2022
	at java.io.FileInputStream.<init>(FileInputStream.java:139)
	at org.apache.commons.vfs2.provider.local.LocalFile.doGetInputStream(LocalFile.java:105)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1197)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1184)
	at org.apache.commons.vfs2.provider.DefaultFileContent.buildInputStream(DefaultFileContent.java:500)
	at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:342)
	at pl.otros.logview.api.io.LoadingInfo.<init>(LoadingInfo.java:58)
	at pl.otros.logview.api.io.LoadingInfo.<init>(LoadingInfo.java:49)
	at pl.otros.logview.gui.actions.TailLogActionListener.openFileObjectInTailMode(TailLogActionListener.java:89)
	at pl.otros.logview.gui.actions.TailLogActionListener.doOpenChooseFileDialog(TailLogActionListener.java:78)
	at pl.otros.logview.gui.actions.TailLogActionListener.actionPerformedHook(TailLogActionListener.java:65)
	at pl.otros.logview.api.gui.OtrosAction.actionPerformed(OtrosAction.java:61)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:108)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at pl.otros.logview.exceptionshandler.EventQueueProxy.dispatchEvent(EventQueueProxy.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#7 server socket at localhost/127.0.0.1:1337 by thread:Attach Listener on Tue Aug 23 19:58:02 CEST 2022
	at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:115)
	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:155)
	at java.net.ServerSocket.createImpl(ServerSocket.java:319)
	at java.net.ServerSocket.getImpl(ServerSocket.java:272)
	at java.net.ServerSocket.bind(ServerSocket.java:390)
	at java.net.ServerSocket.bind(ServerSocket.java:344)
	at org.kohsuke.file_leak_detector.AgentMain.runHttpServer(AgentMain.java:173)
	at org.kohsuke.file_leak_detector.AgentMain.premain(AgentMain.java:158)
	at org.kohsuke.file_leak_detector.AgentMain.agentmain(AgentMain.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
----
```

**Comment by wlfbck** [comment]
I tested both a log that already finished loading as well as a log that was still loading when i closed the tab.

**Comment by wlfbck** [comment]
@svennissel did you have a chance to look at my PR?
