### ISSUE TITLE
stop immediatly after star

### ISSUE THREAD

**Issue by tn76** [otros-systems/otroslogviewer#538]
Hello,
Sorry for my english.
I have a problem with otroslogviewer 1.4.11 (and now with 1.4.10) : the first launches have been succesful but after playing with apparence the application start and stop immediatly.
Is there log file I can post ?
[olv.log](https://github.com/otros-systems/otroslogviewer/files/2282641/olv.log)

**Comment by otros-systems** [comment]
@tn76 Can you provide some environment details:

1. Operating system
2. Java version
3. Java vendor

**Comment by tn76** [comment]
Operating system : windows server standard 2007 SP2
java version: 1.8.0_65
java vendor ? do you mean Oracle ?

Regarding the apparence modifications it seems that the problem occured since I have select windows then go back to the default ligth gray look and feel or may be since I change the size font to 12 pixel ?

Thanks

**Comment by otros-systems** [comment]
I have tried to run with Java 10 on Linux and get following error (in file `$TMP/olv-$USER.log`):
```
Cant invoke method main on class pl.otros.logview.gui.LogViewMainFrame: nulljava.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at pl.otros.starter.StartApp.main(StartApp.java:63)
Caused by: java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at pl.otros.logview.gui.LogViewMainFrame.main(LogViewMainFrame.java:310)
        ... 5 more
Caused by: java.lang.NullPointerException
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)
        at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:661)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installDefaults(SubstancePanelUI.java:74)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.__org__pushingpixels__substance__swingx__SubstancePanelUI__installDefaults(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
        at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:62)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.__org__pushingpixels__substance__swingx__SubstancePanelUI__installUI(SubstancePanelUI.java)
        at org.pushingpixels.substance.swingx.SubstancePanelUI.installUI(SubstancePanelUI.java)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
        at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
        at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
        at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
        at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
        at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
        at java.desktop/javax.swing.JFrame.createRootPane(JFrame.java:279)
        at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:181)
        at pl.otros.logview.gui.LogViewMainFrame.<init>(LogViewMainFrame.java:119)
        at pl.otros.logview.gui.LogViewMainFrame.lambda$main$1(LogViewMainFrame.java:318)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
It looks like Substance 7 exploded on java 10.
@tn76 Can you check file $TMP/olv-$USER.log ?

**Comment by tn76** [comment]
See attached file.
I have several version of JAVA on my pc but my JAVA_HOME points to jre8
[olv.err.3946.txt](https://github.com/otros-systems/otroslogviewer/files/2305242/olv.err.3946.txt)

**Comment by tn76** [comment]
Thanks for this new version.

Perhaps it’s missing some libraries directory ?
lib directory doesn’t exist in scriptsWin directory
and OtrosStarter.jar file doesn’t exist in the project

[cid:image001.png@01D43EE6.1E1C2C30]

Cordialement

Jérôme GUILLEMETTE
Terminaux de Normandie<https://tnterminals.com/>

De : Krzysztof Otrebski [mailto:notifications@github.com]
Envoyé : samedi 25 août 2018 09:18
À : otros-systems/otroslogviewer
Cc : Jérôme Guillemette; Mention
Objet : Re: [otros-systems/otroslogviewer] stop immediatly after star (#538)


@tn76<https://github.com/tn76> Can you confirm that new version is working fine?

**Comment by tn76** [comment]
Everything is OK thanks
