### ISSUE TITLE
Swing null pointer error running olv.bat

### ISSUE THREAD

**Issue by GJS257** [otros-systems/otroslogviewer#565]
I'm getting the following stack dump trying to run olv.bat on win 10. It occurs during startup
Version: 1.4.13
Installed in c:\olv-1.4.13\olv1.4.13
java version "1.8.0_92"

Can't start OtrosLogViewer
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at pl.otros.starter.StartApp.main(StartApp.java:60)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at pl.otros.logview.gui.LogViewMainFrame.main(LogViewMainFrame.java:310)
	... 5 more
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at javax.swing.JEditorPane.registerEditorKitForContentType(Unknown Source)
	at javax.swing.JEditorPane.registerEditorKitForContentType(Unknown Source)
	at javax.swing.JEditorPane.loadDefaultKitsIfNecessary(Unknown Source)
	at javax.swing.JEditorPane.getKitTypeRegistry(Unknown Source)
	at javax.swing.JEditorPane.getEditorKitClassNameForContentType(Unknown Source)
	at javax.swing.JTextPane.<init>(Unknown Source)
	at pl.otros.logview.gui.actions.AboutAction.<init>(AboutAction.java:54)
	at pl.otros.logview.gui.LogViewMainFrame.initMenu(LogViewMainFrame.java:727)
	at pl.otros.logview.gui.LogViewMainFrame.<init>(LogViewMainFrame.java:201)
	at pl.otros.logview.gui.LogViewMainFrame.lambda$main$1(LogViewMainFrame.java:318)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by svennissel** [comment]
This is a bug in JDK. 
https://bugs.openjdk.java.net/browse/JDK-8064444
https://bugs.openjdk.java.net/browse/JDK-8038241

Did you have the problem more than one time?
